#### PROMETEUS on Centos #####

- name: install apache and php
  tags: apache,centos,httpd
  dnf:
    name:
      - httpd
      - php
    state: latest

- name: install mariadb package
  tags: centos,db,mariadb
  dnf:
    name: mariadb-server
    state: latest

- name: restart/enable mariadb
  tags: res_serv,centos
  service:
    name: mariadb
    state: restarted
    enabled: true

- name: start httpd
  tags: centos,httpd
  service:
    name: httpd
    state: started
    enabled: true

- name: install packages
  tags: cent_package
  dnf:
    name:
      - firewalld
      - snapd
    state: latest

- name: install prometheus
  command: sudo snap install prometheus

- name: open 9090 port
  tags: open_9090
  service:
    name: firewalld
    state: restarted
    enabled: true

- name: start prometheus service
  tags: startcent_prome
  shell:
    snap start prometheus

- name: restart prometheus service
  tags: restcent_prome
  shell:
    snap restart prometheus

- name: restart firewalld
  tags: rest_fireld
  service:
    name: firewalld
    state: restarted
    enabled: true

- name: enable EPEL repository
  yum:
    name: epel-release
    state: present

- name: install squashfs-tools
  yum:
    name: squashfs-tools
    state: present

- name: install snapd
  yum:
    name: snapd
    state: present


- name: enable EPEL repository
  yum:
    name: epel-release
    state: present

- name: install squashfs-tools if available
  yum:
    name: squashfs-tools
    state: present
  ignore_errors: true 

- name: download squashfs-tools RPM if not installed
  get_url:
    url: http://vault.centos.org/7.9.2009/os/x86_64/Packages/squashfs-tools-4.3-11.el7.x86_64.rpm
    dest: /tmp/squashfs-tools.rpm
  when: squashfs_tools is failed  

- name: install squashfs-tools from downloaded RPM
  yum:
    name: /tmp/squashfs-tools.rpm
    state: present
  when: squashfs_tools is failed  

